
#define EASYXAXIS 20
#define EASYYAXIS 20
#define EASYMINENUM 100
#define NOLMALXAXIS 30
#define NOLMALXAXIS 30
#define NOLMALMINENUM 400
#define HARDXAXIS 60
#define HARDXAXIS 60
#define HARDMINENUM 3000


char mineENH_Map[EASYYAXIS][EASYXAXIS];